name: Feature request
description: Sugerir nova funcionalidade
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema/oportunidade
      description: Qual dor essa feature resolve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta de solução
      description: Como você imagina a implementação?
      placeholder: Endpoints, UX, impacto técnico.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
      description: Outras opções avaliadas.
  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      options:
        - Alta
        - Média
        - Baixa
    validations:
      required: true
